site_name: imitrix docs
site_url: https://imitrix.de/docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate    
markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "fence_code_format"
        - name: plantuml
          class: plantuml
          format: "fence_code_format"


nav:
  - Home: index.md
