site_name: imitrix docs
site_url: https://imitrix.de/docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate    
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "fence_code_format"
        - name: plantuml
          class: plantuml
          format: "fence_code_format"


nav:
  - Home: index.md
  - Kubernetes Patterns:
    - Behavioral Patterns Intro: kube-behavioral-patterns-intro.md
    - Patterns Part 3: kube-patterns-part3.md
  - Kubernetes Core:
    - Chapter 3 - Deployments: kube-deployment-ch3.md
    - Chapter 4: kube-chap-4.md
    - Chapter 5: kube-chap-5.md
    - Chapter 6: kube-chap-6.md
    - Application: kube-app.md
  - Kubernetes Services:
    - Daemon Service: kube-daemon-service.md
    - Batch Job: kube-batch-job.md
    - Periodic Job: kube-periodic-job.md
  - Infrastructure:
    - Kind Setup: kube-kind.md
    - RKE2 Deployment: rke2-deployment.md
  - Monitoring:
    - Loki: kube-loki.md
  - Tools & References:
    - Kubernetes Cheatsheet: kubecheat.md
    - MkDocs Cheatsheet: mkdocscheat.md
    - Vim Commands: vim-commands.md
  - Other:
    - 30-100: 30-100.md
    - Streamlit Guide: streamlit-guide.md
